apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
spec:
  replicas: 2 
  strategy:
    type: RollingUpdate   
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-website-container
        image: julietok/my_project_image:1.0.0
        ports:
        - containerPort: 8081
        resources:    
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
